p1:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
p2:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
p3:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
p4:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
p5:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
p6:
  - "ge0/0/1"
  - "ge0/0/2"
  - "ge0/0/3"
pe1:
  - "ge0/0/1"
  - "ge0/0/2"
pe2:
  - "ge0/0/1"
  - "ge0/0/2"